[project]
name = "pallets"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "flask",
    "click",
    "marko"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
