name = "David Lord"
nickname = "davidism"
pronouns = "he/they"
picture = "davidism.jpg"
location = "San Diego, California"
tags = ["core", "flask", "jinja", "click", "werkzeug"]
lead = true

[links]
GitHub = "davidism"
Mastodon = "@davidism@mas.to"
Website = "https://davidism.com"
