name = "Phil Jones"
nickname = "pgjones"
tags = ["core", "quart", "flask", "werkzeug"]

[links]
GitHub = "pgjones"
Website = "https://pgjones.dev/"
Mastodon = "@pgjones@fosstodon.org"
Twitter = "pdgjones"
