name = "Markus Unterwaditzer"
nickname = "untitaker"
pronouns = "he/they"
location = "Austria"
tags = ["core", "flask", "click"]
alumni = true

[links]
GitHub = "untitaker"
Mastodon = "@untitaker@woodland.cafe"
Twitter = "untitaker"
